Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,7 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Send POST request for static code analysis
+    - name: Verify environment variables
       env:
         OWNER: ${{ github.repository_owner }}
         REPO: ${{ github.event.repository.name }}
@@ -18,14 +18,26 @@ jobs:
       run: |
         echo "Owner: $OWNER"
         echo "Repo: $REPO"
-        echo "Token: $TOKEN"
-        
-        # response=$(curl -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=${OWNER}&repo=${REPO}&token=${TOKEN}")
-        # echo "Response: $response"
-        # result=$(echo $response | jq '.result')
-        # if [ "$result" != "true" ]; then
-        #   echo "Static code analysis failed."
-        #   exit 1
-        # fi
+        if [ -z "$TOKEN" ]; then
+          echo "TOKEN is not set"
+          exit 1
+        else
+          echo "TOKEN is set"
+        fi
+      shell: bash
+
+    - name: Send POST request for static code analysis
+      env:
+        OWNER: ${{ github.repository_owner }}
+        REPO: ${{ github.event.repository.name }}
+        TOKEN: ${{ secrets.pat_token }}
+      run: |
+        response=$(curl -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=${OWNER}&repo=${REPO}&token=${TOKEN}")
+        echo "Response: $response"
+        result=$(echo $response | jq '.result')
+        if [ "$result" != "true" ]; then
+          echo "Static code analysis failed."
+          exit 1
+        fi
         echo "Static code analysis passed."
       shell: bash
